// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFGes30eV5lsCybf6cLt_J4IpJO1cOKTk',
    appId: '1:394391677732:web:bb0c9e1ecb1bc66d8421b1',
    messagingSenderId: '394391677732',
    projectId: 'localizer-a2d1a',
    authDomain: 'localizer-a2d1a.firebaseapp.com',
    storageBucket: 'localizer-a2d1a.appspot.com',
    measurementId: 'G-HMKK1NET1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8nd00OgYHFH_ZdsvpGo0GnDL8Wj2LD_Y',
    appId: '1:394391677732:android:77ab007b2e0f5f1c8421b1',
    messagingSenderId: '394391677732',
    projectId: 'localizer-a2d1a',
    storageBucket: 'localizer-a2d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqgfy_P6kgRcJojgqSHYV1HOApsuoWpmQ',
    appId: '1:394391677732:ios:c132846ef9f9aed58421b1',
    messagingSenderId: '394391677732',
    projectId: 'localizer-a2d1a',
    storageBucket: 'localizer-a2d1a.appspot.com',
    iosClientId: '394391677732-ddg6cotpeg335n1mmq8bcq3m17pgljnn.apps.googleusercontent.com',
    iosBundleId: 'com.cyberwort.localizer',
  );
}
